# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('recommedationt_text', models.CharField(blank=True, max_length=255)),
                ('timeStamp', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
