# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 08:39
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
