# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20161212_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
